version: "3"

services:
  personal_site_hadel_frontend_prod:
    env_file: ../secrets/personal_site_hadel/frontend_prod.env
    container_name: personal_site_hadel_app_prod
    # command: "tail -f /dev/null"
    # command: bash -c 'npx serve -s build'
    restart: on-failure:5
    build:
      context: ./
      dockerfile: Dockerfile_prod
    volumes:
      - ./:/srv/app
      - /srv/app/.next
    expose:
      - 3000
    networks:
      - nginx_main

networks:
  nginx_main:
    external: true
